name: parser_builder2
description: Generates context-free language parsers in Dart. Currently supports LALR(1) grammars.
version: 0.1.0
repository: https://github.com/tareksander/Dart-Parsertools/tree/main/parser_builder2
issue_tracker: https://github.com/tareksander/Dart-Parsertools/issues
documentation: https://tareksander.github.io/Dart-Parsertools/parser_builder2/index.html


environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  analyzer: ^6.0.0
  build: ^2.0.0
  source_gen: ^1.4.0
  collection: ^1.17.1
  parser_builder2_runtime: ^0.1.0
  source_helper: ^1.3.0

dependency_overrides:
  parser_builder2_runtime:
    path:
      ../parser_builder2_runtime

dev_dependencies:
  lints: ^2.0.0
  dart_flutter_team_lints: ^1.0.0
  dart_style: ^2.0.0
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  test: ^1.21.0
