name: lexer_builder
description: Generate lexer code from regular expression rules.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  analyzer: '>=4.6.0 <6.0.0'
  build: ^2.0.0
  source_gen: ^1.4.0
  collection: ^1.17.1
  lexer_builder_runtime: any

dependency_overrides: 
  lexer_builder_runtime:
    path:
      ../lexer_builder_runtime

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
