name: lexer_builder
description:
  Generate lexer code from regular expression rules.
  Arbitrary custom tokens are supported with generics.

version: 0.1.3
repository: https://github.com/tareksander/Dart-Parsertools/tree/main/lexer_builder
issue_tracker: https://github.com/tareksander/Dart-Parsertools/issues
documentation: https://tareksander.github.io/Dart-Parsertools/lexer_builder/index.html

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  analyzer: ^6.0.0
  build: ^2.0.0
  source_gen: ^1.4.0
  collection: ^1.17.1
  lexer_builder_runtime: ^0.1.0
  source_helper: ^1.3.0

dependency_overrides: 
  #lexer_builder_runtime:
  #  path:
  #    ../lexer_builder_runtime

dev_dependencies:
  lints: ^2.0.0
  #dart_flutter_team_lints: ^1.0.0
  #dart_style: ^2.0.0
  source_gen_test: ^1.0.0
  build_runner: ^2.0.0
  #build_verify: ^3.0.0
  test: ^1.16.0
  #test_descriptor: ^2.0.0
  #test_process: ^2.0.0
